name: wechat_assets_picker
description: An audio/video/image picker in pure Dart which is the same with WeChat, support multi picking.
version: 5.5.8
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #extended_image: ^4.1.0
  extended_image:
    git:
      url: https://github.com/arjun-c-369/extended_image.git
      ref: 378a2d302b0b9c6f391e3c9efd1e9285982910fe
  #photo_manager: ^1.2.3
  photo_manager: ^1.2.3
  #provider: ^5.0.0
  provider:
    git:
      url: https://github.com/arjun-c-369/provider.git
      ref: 9a947855d80263c1edbb62047dfad6e1e9a467d6
  video_player: ^2.1.6
